# (!) DO NOT CHANGE (!)
version: 1

settings:
  language: en_us
  modules:
    kill-summary:
      enabled: true
      show-top-damage: true
      show-others: true
      max-lines: 3
      output: chat # Title, Actionbar, Chat
    pvp-summary:
      enabled: true
      show-combo: true
      show-damage-breakdown: true
      show-damage-recieved: true
      show-damage-dealt: true
      show-kill-weapon: true
      output: chat # Title, Actionbar, Chat
      
